
name: 'my_dbt_project'
version: '1.0'
config-version: 2

profile: 'my_dbt_profile'

model-paths: ["models"]
seed-paths: ["seeds"]

models:
  my_dbt_project:
    staging:
      materialized: view
    marts:
      materialized: table
